name: TinySAM
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - numpy
  - jupyter
  - pip:
    - accelerate
    - loralib
    - yacs
    - addict
    - diffusers
    - gradio
    - huggingface_hub
    - matplotlib
    - numpy
    - Pillow
    - pycocotools
    - PyYAML
    - requests
    - setuptools
    - supervision
    - termcolor
    - timm
    - transformers
    - yapf
    - nltk
    - fairscale
    - litellm
    - torchmetrics
    - matplotlib
    - onnxscript
    - timm
    - bitsandbytes
    - git+https://github.com/facebookresearch/sam2.git
    - git+https://github.com/yformer/EfficientSAM.git
    - git+https://github.com/ChaoningZhang/MobileSAM.git
    - segment-anything-hq
    - git+https://github.com/chongzhou96/EdgeSAM.git
    - git+https://github.com/mit-han-lab/efficientvit.git
